# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae13772ed04acda145d8a74eeed258c70026eadadd13dad83fcbb4541c221101c12174d1d450070c6725ad633633b7f654c2e70713d32fee3d9c51399a15517e

test:
  secret_key_base: 92d748b029de1c5145d31afec9c75b13350297a3987d9d7f824f8454a6ce7a2fbb3558291eae3245542a2499bc362a501320a56298ab59ea1b15dbfc816b2fe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
